### ISSUE TITLE
Virtualenv AssertionError

### ISSUE THREAD

**Issue by darkpixel** [saltstack-formulas/letsencrypt-formula#31]
```
----------
          ID: letsencrypt_packages_pip_virtualenv
    Function: pip.installed
        Name: virtualenv
      Result: False
     Comment: Error installing 'virtualenv': Exception:
              Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
                  status = self.run(options, args)
                File "/usr/lib/python2.7/dist-packages/pip/commands/freeze.py", line 74, in run
                  req = pip.FrozenRequirement.from_dist(dist, dependency_links, find_tags=find_tags)
                File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 299, in from_dist
                  assert len(specs) == 1 and specs[0][0] == '=='
              AssertionError
              
              Storing debug log for failure in /root/.pip/pip.log
     Started: 02:49:07.301772
    Duration: 561.457 ms
     Changes:   
```

**Comment by darkpixel** [comment]
Oops--that's a problem with pip itself, not the formula.
```pip install --upgrade pip```
